// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bmaF0DhYvbJy8W_4K47q_N8kcxfSDH8',
    appId: '1:196058467173:web:dcda49b78606ee92fdaf8c',
    messagingSenderId: '196058467173',
    projectId: 'micro-atrium-416500',
    authDomain: 'micro-atrium-416500.firebaseapp.com',
    storageBucket: 'micro-atrium-416500.appspot.com',
    measurementId: 'G-BRPL44T6M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu8r9Vwb2_VcGM726yR6eyqtNMqprkVy0',
    appId: '1:196058467173:android:9b2c13f44359ecc4fdaf8c',
    messagingSenderId: '196058467173',
    projectId: 'micro-atrium-416500',
    storageBucket: 'micro-atrium-416500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLip5B6dkkJa5GMB_wT3nUUvIgdh-53rM',
    appId: '1:196058467173:ios:68fddab4264528e5fdaf8c',
    messagingSenderId: '196058467173',
    projectId: 'micro-atrium-416500',
    storageBucket: 'micro-atrium-416500.appspot.com',
    androidClientId: '196058467173-a7mgmkn61ql4heclqqra402971iflp41.apps.googleusercontent.com',
    iosClientId: '196058467173-gapojldkdb0ulupk8bpbm5d0vjan416u.apps.googleusercontent.com',
    iosBundleId: 'com.astreos.yinsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLip5B6dkkJa5GMB_wT3nUUvIgdh-53rM',
    appId: '1:196058467173:ios:d15337b9f0ada3bcfdaf8c',
    messagingSenderId: '196058467173',
    projectId: 'micro-atrium-416500',
    storageBucket: 'micro-atrium-416500.appspot.com',
    androidClientId: '196058467173-a7mgmkn61ql4heclqqra402971iflp41.apps.googleusercontent.com',
    iosClientId: '196058467173-inucjrnruhceo7l2a132lq5grt014ios.apps.googleusercontent.com',
    iosBundleId: 'com.example.yinsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6bmaF0DhYvbJy8W_4K47q_N8kcxfSDH8',
    appId: '1:196058467173:web:f90f725c7e36a5cbfdaf8c',
    messagingSenderId: '196058467173',
    projectId: 'micro-atrium-416500',
    authDomain: 'micro-atrium-416500.firebaseapp.com',
    storageBucket: 'micro-atrium-416500.appspot.com',
    measurementId: 'G-L7S2R0SNYF',
  );
}
